### ISSUE TITLE
Close the run on electron:serve

### ISSUE THREAD

**Issue by miyelo** [maximegris/angular-electron#124]
First of all, nice repo, you save us a lot of configuration 🥇 

lately, on my project the application close. I share the log of the crash. 
I can run again, just sometimes dosnt still run.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'electron:serve' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose run-script [ 'preelectron:serve', 'electron:serve', 'postelectron:serve' ]
5 info lifecycle angular-electron@2.0.0~preelectron:serve: angular-electron@2.0.0
6 info lifecycle angular-electron@2.0.0~electron:serve: angular-electron@2.0.0
7 verbose lifecycle angular-electron@2.0.0~electron:serve: unsafe-perm in lifecycle true
8 verbose lifecycle angular-electron@2.0.0~electron:serve: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\if_des1\Desktop\Electron Ts\digitalizacion\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\if_des1\Desktop\Electron Ts\digitalizacion\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\if_des1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\if_des1\AppData\Roaming\npm
9 verbose lifecycle angular-electron@2.0.0~electron:serve: CWD: C:\Users\if_des1\Desktop\Electron Ts\digitalizacion
10 silly lifecycle angular-electron@2.0.0~electron:serve: Args: [ '/d /s /c',
10 silly lifecycle   'npm run build:electron:main && electron ./dist --serve urlArchivo C:\\Users\\if_des1\\Desktop\\pdf.pdf' ]
11 silly lifecycle angular-electron@2.0.0~electron:serve: Returned: code: 3221225477  signal: null
12 info lifecycle angular-electron@2.0.0~electron:serve: Failed to exec electron:serve script
13 verbose stack Error: angular-electron@2.0.0 electron:serve: `npm run build:electron:main && electron ./dist --serve urlArchivo C:\Users\if_des1\Desktop\pdf.pdf`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid angular-electron@2.0.0
15 verbose cwd C:\Users\if_des1\Desktop\Electron Ts\digitalizacion
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "electron:serve"
18 verbose node v8.7.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 3221225477
22 error angular-electron@2.0.0 electron:serve: `npm run build:electron:main && electron ./dist --serve urlArchivo C:\Users\if_des1\Desktop\pdf.pdf`
22 error Exit status 3221225477
23 error Failed at the angular-electron@2.0.0 electron:serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]

```

**Comment by miyelo** [comment]
I think is how i start my app. 
When send to run 2 windows will open, when i close the last one before the electron:serve run, no problem. maybe is in the paralell who dosnt know what electron window point.

**Comment by maximegris** [comment]
Thanks for this feedback. :)
