### ISSUE TITLE
Can't build app for mac (right after cloning the repo)

### ISSUE THREAD

**Issue by sharikovvladislav** [maximegris/angular-electron#137]
Hey!

I cloned the repo, installed the deps and I tried to build mac executable. I got error.

Here is the output:

```
svlad at sharikovvlad in ~/sandbox
$ git clone https://github.com/maximegris/angular-electron.git
Cloning into 'angular-electron'...
remote: Counting objects: 712, done.
remote: Total 712 (delta 0), reused 0 (delta 0), pack-reused 712
Receiving objects: 100% (712/712), 1.13 MiB | 378.00 KiB/s, done.
Resolving deltas: 100% (414/414), done.

svlad at sharikovvlad in ~/sandbox
$ cd angul
angular-electron/           angular-seed/               angular2-task-manager/      angularjs-caching-research/

svlad at sharikovvlad in ~/sandbox
$ cd angular-electron/

svlad at sharikovvlad in ~/sandbox/angular-electron on master
$ npm i
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> fsevents@1.1.3 install /Users/svlad/sandbox/angular-electron/node_modules/fsevents
> node install

[fsevents] Success: "/Users/svlad/sandbox/angular-electron/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uws@9.14.0 install /Users/svlad/sandbox/angular-electron/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.7.2 install /Users/svlad/sandbox/angular-electron/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/svlad/.npm/node-sass/4.7.2/darwin-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/svlad/sandbox/angular-electron/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall /Users/svlad/sandbox/angular-electron/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/svlad/sandbox/angular-electron/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> electron@1.8.2 postinstall /Users/svlad/sandbox/angular-electron/node_modules/electron
> node install.js

Downloading SHASUMS256.txt
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)

> angular-electron@3.0.0 postinstall /Users/svlad/sandbox/angular-electron
> npx electron-builder install-app-deps

  • electron-builder version=20.0.5
  • loaded configuration file=/Users/svlad/sandbox/angular-electron/electron-builder.json
  • no native production dependencies
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.3.5 (node_modules/app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.3.5: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.3.5 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.3.5: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

added 2093 packages in 90.233s

svlad at sharikovvlad in ~/sandbox/angular-electron on master
$ npm run build:mac
npm ERR! missing script: build:mac

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svlad/.npm/_logs/2018-03-04T21_56_09_746Z-debug.log

svlad at sharikovvlad in ~/sandbox/angular-electron on master
$ npm run electron:mac

> angular-electron@3.0.0 electron:mac /Users/svlad/sandbox/angular-electron
> npm run build:prod && npx electron-builder build --mac


> angular-electron@3.0.0 build:prod /Users/svlad/sandbox/angular-electron
> node hooks/environments/set_profile.js && ng build --prod && npm run electron:tsc

Déplacement du template de fichier de détection de configuration ...
Application du profil : local
Date: 2018-03-04T21:56:47.726Z
Hash: 16144c87e46199d7b190
Time: 21580ms
chunk {0} main.c19ad11efa54f8d34768.bundle.js (main) 388 kB [initial] [rendered]
chunk {1} polyfills.c0980d5bca1568dc0b1d.bundle.js (polyfills) 72.3 kB [initial] [rendered]
chunk {2} styles.20687cb7c9b35e360877.bundle.css (styles) 41 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

> angular-electron@3.0.0 electron:tsc /Users/svlad/sandbox/angular-electron
> tsc main.ts

  • electron-builder version=20.0.5
  • loaded configuration file=/Users/svlad/sandbox/angular-electron/electron-builder.json
  • writing effective config file=app-builds/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=1.8.2 appOutDir=app-builds/mac
Downloading tmp-22906-1-SHASUMS256.txt-1.8.2
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)
  ⨯ icon source "dist/favicon" not found
github.com/develar/app-builder/pkg/icons.resolveSourceFile
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:110
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:160
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:27
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:57
runtime.main
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/proc.go:195
runtime.goexit
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:162
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Users/develar/go/src/github.com/develar/app-builder/pkg/icons/icon-converter.go:27
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
	/Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:57
runtime.main
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/proc.go:195
runtime.goexit
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/asm_amd64.s:2337

Error: /Users/svlad/sandbox/angular-electron/node_modules/app-builder-bin-mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/Users/svlad/sandbox/angular-electron/node_modules/builder-util/src/util.ts:248:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at MacPackager.resolveIcon (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/platformPackager.js:610:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/platformPackager.ts:562:36
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.getOrConvertIcon (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/platformPackager.js:587:11)
    at Lazy.MacPackager._iconPath.Lazy (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/macPackager.ts:39:43)
    at Lazy.get value [as value] (/Users/svlad/sandbox/angular-electron/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/macPackager.ts:55:27
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.getIconPath (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/macPackager.js:146:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/packager/mac.ts:67:31
    at Generator.next (<anonymous>)
    at /Users/svlad/sandbox/angular-electron/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
From previous event:
    at createMacApp (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/packager/mac.js:142:21)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/macPackager.ts:263:11
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.beforeCopyExtraFiles (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/macPackager.js:364:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/platformPackager.ts:202:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacPackager.doPack (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/platformPackager.js:268:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/macPackager.ts:93:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/macPackager.js:209:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/svlad/sandbox/angular-electron/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/svlad/sandbox/angular-electron/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/packager.js:441:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /Users/svlad/sandbox/angular-electron/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/svlad/sandbox/angular-electron/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/packager.js:385:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/packager.js:341:11)
    at /Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/svlad/sandbox/angular-electron/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at findNodeScript.then.existing (/Users/svlad/sandbox/angular-electron/node_modules/npx/node_modules/libnpx/index.js:268:14)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@3.0.0 electron:mac: `npm run build:prod && npx electron-builder build --mac`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@3.0.0 electron:mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svlad/.npm/_logs/2018-03-04T21_57_24_978Z-debug.log
```

**Comment by hervehobbes** [comment]
Hello,

Same error for me.
Just clone the repository + npm install + npm run electron:mac

**Comment by maximegris** [comment]
Indeed.
Plese pull the repo or apply changes of commit https://github.com/maximegris/angular-electron/commit/22699efd6a5acc6c30ae1b2713228192af4d523a

It should fix the error. Thanks !

**Comment by hervehobbes** [comment]
It runs, thanks again.

**Comment by maximegris** [comment]
You're welcome :)

**Comment by mherb63** [comment]
I know this issue has been closed, but its happening again with the latest.

```
From previous event:
    at Object.args [as handler] (/Users/mherb/Documents/ElectronApps/angular-electron/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/mherb/Documents/ElectronApps/angular-electron/node_modules/electron-builder/node_modules/yargs/lib/command.js:237:44)
    at Object.parseArgs [as _parseArgs] (/Users/mherb/Documents/ElectronApps/angular-electron/node_modules/electron-builder/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/Users/mherb/Documents/ElectronApps/angular-electron/node_modules/electron-builder/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/mherb/Documents/ElectronApps/angular-electron/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at findNodeScript.then.existing (/Users/mherb/Documents/ElectronApps/angular-electron/node_modules/npx/node_modules/libnpx/index.js:268:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@4.2.2 electron:mac: `npm run build:prod && npx electron-builder build --mac`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-electron@4.2.2 electron:mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
