### ISSUE TITLE
Build on Linux fail

### ISSUE THREAD

**Issue by hervehobbes** [maximegris/angular-electron#138]
Hello,

When typing npm run electron:linux I have this error message:

> icon directory /home/herve/Dev/electron/dist doesn't contain icons

Any idea what to do?

**Comment by NizarBsb** [comment]
Build on Linux is definitely broken with the latest changes:

> app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/projects/node_modules/builder-util/src/util.ts:248:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by maximegris** [comment]
Indeed.
Plese pull the repo or apply changes of commit https://github.com/maximegris/angular-electron/commit/22699efd6a5acc6c30ae1b2713228192af4d523a

It should fix the error. Thanks !

**Comment by NizarBsb** [comment]
Thank you @maximegris, this is now working flawlessly!

**Comment by hervehobbes** [comment]
Thank you very much.

**Comment by maximegris** [comment]
You're welcome :)
