### ISSUE TITLE
build error when change the version in package.json

### ISSUE THREAD

**Issue by dxwts** [maximegris/angular-electron#159]
I change the version value and build app for windows get error, restore is ok.
Can anyone help?
Thanks!

```
"version": "3.1.0",  -> "version": "3.1.1"
```

```
$ yarn run electron:windows
yarn run v1.3.2
$ npm run build:prod && npx electron-builder build --windows

> angular-electron@3.1.1 build:prod D:\workspace\electron\angular-electron
> node hooks/environments/set_profile.js && ng build --prod && npm run electron:tsc

Déplacement du template de fichier de détection de configuration ...
Application du profil : local
Date: 2018-04-03T09:19:32.632Z
Hash: cd6d306dc2333311eeb4
Time: 4835ms
chunk {0} main.3e29f1fceccb78718b88.bundle.js (main) 388 kB [initial] [rendered]
chunk {1} polyfills.c0980d5bca1568dc0b1d.bundle.js (polyfills) 72.3 kB [initial] [rendered]
chunk {2} styles.20687cb7c9b35e360877.bundle.css (styles) 41 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

> angular-electron@3.1.1 electron:tsc D:\workspace\electron\angular-electron
> tsc main.ts

D:\workspace\electron\angular-electron\node_modules\electron-builder\out\cli\cli.js
  • electron-builder version=20.0.5
  • loaded configuration file=D:\workspace\electron\angular-electron\electron-builder.json
  • writing effective config file=app-builds\electron-builder.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.2 appOutDir=app-builds\win-unpacked
Error: Exit code: 1. Command failed: C:\Users\dxwts\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0\rcedit.exe D:\workspace\electron\angular-electron\app-builds\win-unpacked\angular-electron.exe --set-version-string FileDescription angular-electron --s
et-version-string ProductName angular-electron --set-version-string LegalCopyright Copyright © 2018 Maxime GRIS --set-file-version 3.1.1 --set-product-version 3.1.1.0 --set-version-string InternalName angular-electron --set-version-string OriginalFilename  --set-version-
string CompanyName Maxime GRIS --set-icon D:\workspace\electron\angular-electron\app-builds\.icon-ico\icon.ico
Fatal error: Unable to commit changes

Fatal error: Unable to commit changes

    at D:\workspace\electron\angular-electron\node_modules\builder-util\src\util.ts:124:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.signAndEditResources (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\winPackager.js:405:11)
    at D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\src\winPackager.ts:343:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\winPackager.js:423:11)
    at D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\src\platformPackager.ts:211:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\platformPackager.js:268:11)
    at D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\src\platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\platformPackager.js:188:11)
    at D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\src\packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.stat (D:\workspace\electron\angular-electron\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at D:\workspace\electron\angular-electron\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\packager.js:441:11)
    at D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\src\packager.ts:316:52
    at Generator.next (<anonymous>)
    at D:\workspace\electron\angular-electron\node_modules\graceful-fs\graceful-fs.js:99:16
    at D:\workspace\electron\angular-electron\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\packager.js:385:11)
    at D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\src\packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\packager.js:341:11)
    at D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\src\index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (D:\workspace\electron\angular-electron\node_modules\electron-builder-lib\out\index.js:47:21)
    at build (D:\workspace\electron\angular-electron\node_modules\electron-builder\src\builder.ts:228:10)
    at then (D:\workspace\electron\angular-electron\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (D:\workspace\electron\angular-electron\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (D:\workspace\electron\angular-electron\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (D:\workspace\electron\angular-electron\node_modules\electron-builder\node_modules\yargs\yargs.js:1014:30)
    at Object.get [as argv] (D:\workspace\electron\angular-electron\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (D:\workspace\electron\angular-electron\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at findNodeScript.then.existing (D:\workspace\electron\angular-electron\node_modules\npx\node_modules\libnpx\index.js:268:14)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

**Comment by cjackson234** [comment]
This is a permissions issue with electron builder. See here: https://github.com/electron-userland/electron-builder/issues/2328

**Comment by dxwts** [comment]
Thanks， I restart computer，the issue solved.
