### ISSUE TITLE
Error: npm run e2e

### ISSUE THREAD

**Issue by seopei** [maximegris/angular-electron#163]
If I run `npm run e2e` I will get an error:

```
npm run e2e                                                                                                                 09.04.2018 20:56:26

> angular-electron@3.1.0 e2e /Users/sebastian/develop/angular-electron
> npm-run-all -p pree2e:build pree2e:protractor


> angular-electron@3.1.0 pree2e:build /Users/sebastian/develop/angular-electron
> webdriver-manager update --gecko false && npm run ng:serve


> angular-electron@3.1.0 pree2e:protractor /Users/sebastian/develop/angular-electron
> wait-on http-get://localhost:4200/ && protractor ./protractor.conf.js

[20:56:50] I/file_manager - creating folder /Users/sebastian/develop/angular-electron/node_modules/webdriver-manager/selenium
[20:56:57] I/update - chromedriver: unzipping chromedriver_2.37.zip
[20:56:57] I/update - chromedriver: setting permissions to 0755 for /Users/sebastian/develop/angular-electron/node_modules/webdriver-manager/selenium/chromedriver_2.37

> angular-electron@3.1.0 ng:serve /Users/sebastian/develop/angular-electron
> ng serve -o

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 4/4 modules 0 activewebpack: wait until bundle finished: /
 12% building modules 22/23 modules 1 active ...n/node_modules/webpack/hot/emitter.jswebpack: wait until bundle finished: /
Date: 2018-04-09T18:57:24.971Z
Hash: 687c5ae4039c4b615b64
Time: 13422ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 50.6 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 639 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 42.4 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 10.7 MB [initial] [rendered]

webpack: Compiled successfully.
(node:74185) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[20:57:27] I/launcher - Running 1 instances of WebDriver
[20:57:27] I/direct - Using ChromeDriver directly...
Jasmine started

  angular-electron App
    ✗ should display message saying App works !
      - Failed: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
          at runWaitForAngularScript.then (/Users/sebastian/develop/angular-electron/node_modules/protractor/built/browser.js:463:23)
          at ManagedPromise.invokeCallback_ (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at asyncRun (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:2927:27)
          at /Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)Error
          at ElementArrayFinder.applyAction_ (/Users/sebastian/develop/angular-electron/node_modules/protractor/built/element.js:459:27)
          at ElementArrayFinder.(anonymous function).args [as getText] (/Users/sebastian/develop/angular-electron/node_modules/protractor/built/element.js:91:29)
          at ElementFinder.(anonymous function).args [as getText] (/Users/sebastian/develop/angular-electron/node_modules/protractor/built/element.js:831:22)
          at UserContext.<anonymous> (/Users/sebastian/develop/angular-electron/e2e/app.e2e-spec.ts:11:73)
          at /Users/sebastian/develop/angular-electron/node_modules/jasminewd2/index.js:112:25
          at new ManagedPromise (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:1077:7)
          at ControlFlow.promise (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:2505:12)
          at schedulerExecute (/Users/sebastian/develop/angular-electron/node_modules/jasminewd2/index.js:95:18)
          at TaskQueue.execute_ (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      From: Task: Run it("should display message saying App works !") in control flow
          at UserContext.<anonymous> (/Users/sebastian/develop/angular-electron/node_modules/jasminewd2/index.js:94:19)
          at /Users/sebastian/develop/angular-electron/node_modules/jasminewd2/index.js:64:48
          at ControlFlow.emit (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/events.js:62:21)
          at ControlFlow.shutdown_ (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:2674:10)
          at shutdownTask_.MicroTask (/Users/sebastian/develop/angular-electron/node_modules/selenium-webdriver/lib/promise.js:2599:53)
      From asynchronous test:
      Error
          at Suite.<anonymous> (/Users/sebastian/develop/angular-electron/e2e/app.e2e-spec.ts:10:5)
          at Object.<anonymous> (/Users/sebastian/develop/angular-electron/e2e/app.e2e-spec.ts:5:1)
          at Module._compile (module.js:643:30)
          at Module.m._compile (/Users/sebastian/develop/angular-electron/node_modules/ts-node/src/index.ts:422:23)
          at Module._extensions..js (module.js:654:10)
          at Object.require.extensions.(anonymous function) [as .ts] (/Users/sebastian/develop/angular-electron/node_modules/ts-node/src/index.ts:425:12)

**************************************************
*                    Failures                    *
**************************************************

1) angular-electron App should display message saying App works !
  - Failed: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"

Executed 1 of 1 spec (1 FAILED) in 0.036 sec.
[20:57:28] I/launcher - 0 instance(s) of WebDriver still running
[20:57:28] I/launcher - chrome #01 failed 1 test(s)
[20:57:28] I/launcher - overall: 1 failed spec(s)
[20:57:28] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@3.1.0 pree2e:protractor: `wait-on http-get://localhost:4200/ && protractor ./protractor.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@3.1.0 pree2e:protractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastian/.npm/_logs/2018-04-09T18_57_28_653Z-debug.log
ERROR: "pree2e:protractor" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@3.1.0 e2e: `npm-run-all -p pree2e:build pree2e:protractor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@3.1.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastian/.npm/_logs/2018-04-09T18_57_28_819Z-debug.log
```

**Comment by seopei** [comment]
PR #161 will fix this.
