### ISSUE TITLE
npm electron:prod and electron:mac fail to build

### ISSUE THREAD

**Issue by skwh** [maximegris/angular-electron#168]
Hi,
Trying to build [my app](https://github.com/skwh/groupme-client) for prod / distribution, however, I get a strange NPM error that doesn't seem to offer much helpful information:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/Evan/.nvm/versions/node/v8.1.3/bin/node',
1 verbose cli   '/Users/Evan/.nvm/versions/node/v8.1.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@5.5.1
3 info using node@v8.1.3
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle groupme-client@0.8.5~prebuild:prod: groupme-client@0.8.5
6 info lifecycle groupme-client@0.8.5~build:prod: groupme-client@0.8.5
7 verbose lifecycle groupme-client@0.8.5~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle groupme-client@0.8.5~build:prod: PATH: /Users/Evan/.nvm/versions/node/v8.1.3/lib/node_modules/npm/bin/node-gyp-bin:/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/.bin:/Users/Evan/.nvm/versions/node/v8.1.3/lib/node_modules/npm/bin/node-gyp-bin:/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/.bin:/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/electron/dist/Electron.app/Contents/MacOS:/Users/Evan/.nvm/versions/node/v8.1.3/bin:/Users/Evan/.rvm/gems/ruby-2.0.0-p643/bin:/Users/Evan/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/Evan/.rvm/rubies/ruby-2.0.0-p643/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin:/Library/TeX/texbin:/Users/Evan/.rvm/bin:/Users/Evan/.rvm/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/sbin:/Users/Evan/.nvm/versions/node/v8.1.3/bin
9 verbose lifecycle groupme-client@0.8.5~build:prod: CWD: /Users/Evan/Documents/Programming/electron/groupme-client
10 silly lifecycle groupme-client@0.8.5~build:prod: Args: [ '-c', 'cross-env NODE_ENV=production npm run build' ]
11 silly lifecycle groupme-client@0.8.5~build:prod: Returned: code: 2  signal: null
12 info lifecycle groupme-client@0.8.5~build:prod: Failed to exec build:prod script
13 verbose stack Error: groupme-client@0.8.5 build:prod: `cross-env NODE_ENV=production npm run build`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/Evan/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/Evan/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid groupme-client@0.8.5
15 verbose cwd /Users/Evan/Documents/Programming/electron/groupme-client
16 verbose Darwin 16.7.0
17 verbose argv "/Users/Evan/.nvm/versions/node/v8.1.3/bin/node" "/Users/Evan/.nvm/versions/node/v8.1.3/bin/npm" "run" "build:prod"
18 verbose node v8.1.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error groupme-client@0.8.5 build:prod: `cross-env NODE_ENV=production npm run build`
22 error Exit status 2
23 error Failed at the groupme-client@0.8.5 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

my app runs fine otherwise with `npm electron:dev` and through the hot-reload build script. Can you help? Thanks

**Comment by maximegris** [comment]
Can yo utry to reinstall your node_modules packages ?

rm -rf node_modules
rm package-lock.json
npm cache clear --force
npm install
cross-env ENV=prod ***THE NPM SCRIPT***

**Comment by skwh** [comment]
I received this message after the `npm install` step:

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @angular-devkit/schematics@0.0.52 requires a peer of @angular-devkit/core@0.0.29 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none is installed. You must install peer dependencies yourself.
```

Running the script again afterwards produces the same error as in my original comment.

**Comment by skwh** [comment]
Hi, I saw that after installing these packages the `npm run` log started becoming more verbose about the issue. There were Typescript errors in some of my components that I needed to fix, which I did. Now I am receiving this message about `flags`:

```
ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module build failed: TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:23972:36)
    at checkAliasSymbol (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:42658:26)
    at checkImportBinding (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:42688:13)
    at checkImportDeclaration (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:42706:29)
    at checkSourceElement (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:43018:28)
    at Object.forEach (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:1499:30)
    at checkSourceFileWorker (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:43091:20)
    at checkSourceFile (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:43071:13)
    at getDiagnosticsWorker (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:43135:17)
    at getDiagnostics (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:43121:24)
    at Object.getEmitResolver (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:23049:13)
    at /Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70489:69
    at runWithCancellationToken (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70245:24)
    at getDeclarationDiagnosticsForFileNoCache (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70488:20)
    at getAndCacheDiagnostics (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70501:26)
    at getDeclarationDiagnosticsWorker (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70485:20)
    at getDeclarationDiagnosticsForFile (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70514:56)
    at getDiagnosticsHelper (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70204:24)
    at Object.getDeclarationDiagnostics (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/typescript/lib/typescript.js:70226:24)
    at TypeScriptFileRefactor.getDiagnostics (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/@ngtools/webpack/src/refactor.js:52:60)
    at Promise.resolve.then.then.then.then (/Users/Evan/Documents/Programming/electron/groupme-client/node_modules/@ngtools/webpack/src/loader.js:481:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```
