### ISSUE TITLE
NG scss build fail

### ISSUE THREAD

**Issue by Jorropo** [maximegris/angular-electron#217]
# Versions :
Ubuntu 18 (64bits)
Nodejs v8.10.0 (64bits)

# The error
When I try to build I got this error :
```
> angular-electron@4.1.0 ng:serve:web /home/$USER/Documents/Scripts/angular-electron
> npm run postinstall:web && ng serve -o


> angular-electron@4.1.0 postinstall:web /home/$USER/Documents/Scripts/angular-electron
> node postinstall-web

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2018-07-18T18:41:55.718Z
Hash: 7fc75582531d5e853d5a
Time: 14913ms
chunk {main} main.js, main.js.map (main) 271 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 245 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.2 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.91 MB [initial] [rendered]

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'crypto' in '/home/$USER/Documents/Scripts/angular-electron/node_modules/zone.js/dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'fs' in '/home/$USER/Documents/Scripts/angular-electron/node_modules/zone.js/dist'

WARNING in ./node_modules/zone.js/dist/zone-mix.js
Module not found: Error: Can't resolve 'timers' in '/home/$USER/Documents/Scripts/angular-electron/node_modules/zone.js/dist'

ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.sassLoader (/home/$USER/Documents/Scripts/angular-electron/node_modules/sass-loader/lib/loader.js:24:22)
ERROR in ./src/app/app.component.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.sassLoader (/home/$USER/Documents/Scripts/angular-electron/node_modules/sass-loader/lib/loader.js:24:22)
ERROR in ./src/app/components/home/home.component.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/$USER/Documents/Scripts/angular-electron/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.sassLoader (/home/$USER/Documents/Scripts/angular-electron/node_modules/sass-loader/lib/loader.js:24:22)
ℹ ｢wdm｣: Failed to compile.
```
# Reproduce step :
```sh
git clone --recursive https://github.com/maximegris/angular-electron && cd angular-electron/ && rm -rf .git/ && git init && git add . && git commit -m "Initial Commit" && sudo npm install -g @angular/cli && npm install && npm run ng:serve:web && npm run postinstall:electron && npm run electron:tsc && npm run ng:serve:web
```
I does ```npm run postinstall:electron && npm run electron:tsc``` cause I where getting this error but with a message asking me to do this.

**Comment by Jorropo** [comment]
Apparently the error already have been see and solve here [github.com/angular/angular-cli/issues/9642](https://github.com/angular/angular-cli/issues/9642).
But I don't understand cause I'm an noob in web client framework.
