### ISSUE TITLE
npm install frequently erroring

### ISSUE THREAD

**Issue by edcolyer** [maximegris/angular-electron#295]
I am frequently getting compiler errors when using `npm install` with angular-electron master branch. I'm on macOS Mojave 10.14.2.

E.g. executing `npm install --save auth0/angular-jwt` results in this output:

```
> fsevents@1.2.4 install /Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents
> node install

  SOLINK_MODULE(target) Release/.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/edcolyer/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/edcolyer/.nvm/versions/node/v8.11.3/bin/node" "/Users/edcolyer/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/lib/binding/Release/electron-v1.2-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/lib/binding/Release/electron-v1.2-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/edcolyer/.nvm/versions/node/v8.11.3/bin/node /Users/edcolyer/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/lib/binding/Release/electron-v1.2-darwin-x64/fse.node --module_name=fse --module_path=/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/lib/binding/Release/electron-v1.2-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/Users/edcolyer/.nvm/versions/node/v8.11.3/bin/node" "/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/edcolyer/.nvm/versions/node/v8.11.3/bin/node /Users/edcolyer/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/lib/binding/Release/electron-v1.2-darwin-x64/fse.node --module_name=fse --module_path=/Users/edcolyer/Documents/Web/cb-connect-client/node_modules/fsevents/lib/binding/Release/electron-v1.2-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm WARN @angular/animations@7.1.4 requires a peer of @angular/core@7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ angular-jwt@0.1.10
updated 1 package and audited 43345 packages in 14.927s
found 0 vulnerabilities
```

This is also happening for various other npm packages, including `electron-json-storage` and `keytar`.

**Comment by isurendrasingh** [comment]
Your Node & npm are outdated. Try to update them to latest versions and the errors will be gone.

**Comment by edcolyer** [comment]
That was the issue. Thanks.
