### ISSUE TITLE
Failure on Post Install

### ISSUE THREAD

**Issue by RacerDelux** [maximegris/angular-electron#310]
npm install is failing on postintsall script. Not sure how to go about fixing this.
```
pps;C:\Users\jeffb\AppData\Roaming\npm;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\cmdr
672 verbose lifecycle ArcMages@5.1.0~postinstall: CWD: C:\Repositories\ArcMages\arcmages-client
673 silly lifecycle ArcMages@5.1.0~postinstall: Args: [ '/d /s /c',
673 silly lifecycle   'npm run postinstall:electron && electron-builder install-app-deps' ]
674 silly lifecycle ArcMages@5.1.0~postinstall: Returned: code: 1  signal: null
675 info lifecycle ArcMages@5.1.0~postinstall: Failed to exec postinstall script
676 verbose stack Error: ArcMages@5.1.0 postinstall: `npm run postinstall:electron && electron-builder install-app-deps`
676 verbose stack Exit status 1
676 verbose stack     at EventEmitter.<anonymous> (C:\Users\jeffb\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
676 verbose stack     at EventEmitter.emit (events.js:182:13)
676 verbose stack     at ChildProcess.<anonymous> (C:\Users\jeffb\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
676 verbose stack     at ChildProcess.emit (events.js:182:13)
676 verbose stack     at maybeClose (internal/child_process.js:962:16)
676 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
677 verbose pkgid ArcMages@5.1.0
678 verbose cwd C:\Repositories\ArcMages\arcmages-client
679 verbose Windows_NT 10.0.17763
680 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jeffb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
681 verbose node v10.15.0
682 verbose npm  v6.8.0
683 error code ELIFECYCLE
684 error errno 1
685 error ArcMages@5.1.0 postinstall: `npm run postinstall:electron && electron-builder install-app-deps`
685 error Exit status 1
686 error Failed at the ArcMages@5.1.0 postinstall script.
686 error This is probably not a problem with npm. There is likely additional logging output above.
687 verbose exit [ 1, true ]
```
https://pastebin.com/jLfHHBSH

**Comment by RacerDelux** [comment]
It looks like the top error is 
`Error: Unresolved node modules: register-scheme`
