### ISSUE TITLE
Windows Build fails

### ISSUE THREAD

**Issue by appskitchen** [maximegris/angular-electron#342]
Hi,
 I've cloned the repo and installed the packages. Then I tried the following command - 
`npm run build:prod && electron-builder build --windows`

but after certain successful steps, it fails. here is the log - 
```
PS C:\Users\musa\Desktop\Dev\ngular-electron> npm run electron:windows

> angular-electron@5.1.0 electron:windows C:\Users\musa\Desktop\Dev\ngular-electron
> npm run build:prod && electron-builder build --windows


> angular-electron@5.1.0 build:prod C:\Users\musa\Desktop\Dev\ngular-electron
> npm run build -- -c production


> angular-electron@5.1.0 build C:\Users\musa\Desktop\Dev\ngular-electron
> npm run postinstall:electron && npm run electron:serve-tsc && ng build "-c" "production"


> angular-electron@5.1.0 postinstall:electron C:\Users\musa\Desktop\Dev\ngular-electron
> node postinstall


> angular-electron@5.1.0 electron:serve-tsc C:\Users\musa\Desktop\Dev\ngular-electron
> tsc -p tsconfig-serve.json


Date: 2019-05-22T19:15:42.222Z
Hash: b59067ad5a3f1fb6140b
Time: 32470ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.5ee71e0b7b0794856a9f.js (main) 342 kB [initial] [rendered]
chunk {2} polyfills.9d3a8743be9f041e6ba8.js (polyfills) 41 kB [initial] [rendered]
chunk {3} styles.f31adf291ee27cc08f94.css (styles) 41 bytes [initial] [rendered]
  • electron-builder version=20.36.2
  • loaded configuration file=C:\Users\musa\Desktop\Dev\ngular-electron\electron-builder.json
  • writing effective config file=release\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=4.0.0 appOutDir=release\win-unpacked
  • building        target=portable file=release\angular-electron 5.1.0.exe archs=x64
  • downloading               parts=1 size=1.4 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z
  • downloaded                duration=8.767s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z
  • cannot move downloaded into final location (another process downloaded faster?) error=rename C:\Users\musa\AppData\Local\electron-builder\Cache\nsis\713354511 C:\Users\musa\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2: Access is denied. path=C:\Users\musa\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2 tempFile=C:\Users\musa\AppData\Local\electron-builder\Cache\nsis\713354511
Error: ENOENT: no such file or directory, copyfile 'C:\Users\musa\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\elevate.exe' -> 'C:\Users\musa\Desktop\Dev\ngular-electron\release\win-unpacked\resources\elevate.exe'
    at doCopyFile (C:\Users\musa\Desktop\Dev\ngular-electron\node_modules\builder-util\src\fs.ts:218:19)
    at copyOrLinkFile (C:\Users\musa\Desktop\Dev\ngular-electron\node_modules\builder-util\src\fs.ts:200:10)
    at then (C:\Users\musa\Desktop\Dev\ngular-electron\node_modules\builder-util\src\fs.ts:144:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@5.1.0 electron:windows: `npm run build:prod && electron-builder build --windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@5.1.0 electron:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\musa\AppData\Roaming\npm-cache\_logs\2019-05-22T19_16_07_498Z-debug.log
```
Any idea?
Thanks

**Comment by nikhilnxvverma1** [comment]
Looks like you need admin privileges. Can you run the same command as admin?

**Comment by appskitchen** [comment]
@nikhilnxvverma1 Not really, I opened the command line as admin.

**Comment by steinsag** [comment]
Is this still an issue or can it be closed? I tried today on Win 10 64Bit with a non-admin user and it worked without any problems. I basically did:

    npm install -g @angular/cli
    npm install
    npm run electron:windows

And it generated a Windows executable in **release** folder.

For reference, I'm using latest nodejs versions:

- node - 10.16.3
- npm - 6.9.0

**Comment by varunjayakumar** [comment]
I have the same issue with electronjs packaging and get the issue using yarn and npm. Admin mode isn't helping. Cmd used: "yarn dist", also tried "npm run dist". Kindly, help.

error=rename C:\Users\vjayakum\AppData\Local\electron-builder\Cache\nsis\123078191 C:\Users\vjayakum\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2: Access is denied.

**Comment by txtcbenne** [comment]
Can you disable any antivirus scanning and try again?
