### ISSUE TITLE
Setting target es6 breaks the app build

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#360]
If I set typescript to target es2015 using:

```"target": "es6"```

the `npm start` command fails with:

```
> tsc -p tsconfig-serve.json

App threw an error during load
/home/shin/sources/Keira3/main.js:1
import { app, BrowserWindow, screen } from 'electron';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:752:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/home/shin/sources/Keira3/node_modules/electron/dist/resources/default_app.asar/main.js:105:12)
    at Object.<anonymous> (/home/shin/sources/Keira3/node_modules/electron/dist/resources/default_app.asar/main.js:153:5)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
A JavaScript error occurred in the main process
Uncaught Exception:
/home/shin/sources/Keira3/main.js:1
import { app, BrowserWindow, screen } from 'electron';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:752:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/home/shin/sources/Keira3/node_modules/electron/dist/resources/default_app.asar/main.js:105:12)
    at Object.<anonymous> (/home/shin/sources/Keira3/node_modules/electron/dist/resources/default_app.asar/main.js:153:5)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
```

**Comment by MusicDev33** [comment]
I'd check this out: 
https://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import

**Comment by MusicDev33** [comment]
So I've looked into this a bit more, and it looks like the main problem stems from Node not recognizing ES6, and the only solutions I've seen are Babel or a lot of refactoring.

**Comment by MusicDev33** [comment]
This commit seems to solve, it builds and works:
https://github.com/maximegris/angular-electron/pull/322/commits/9174857bd01147753c9909abdfe48adcef5053be
