### ISSUE TITLE
Error while compiling -  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by peiying98** [maximegris/angular-electron#380]
Hello! I'm new to Angular and was trying to compile and run the sample app but was faced with this error:

ERROR in RangeError: Maximum call stack size exceeded
    at checkDiagnostics (...\angular-electron\node_modules\@ngtools\webpack\src\gather_diagnostics.js:40:32)
    at Object.gatherDiagnostics (...\angular-electron\node_modules\@ngtools\webpack\src\gather_diagnostics.js:67:13)
    at AngularCompilerPlugin._emit (...\angular-electron\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:1034:61)
    at AngularCompilerPlugin._update (...\angular-electron\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:804:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I've tried some methods online to resolve this compilation problem but none seem to work.  Would greatly appreciate any ideas on solving this error! Thank you!

**Comment by harmandeep-singh** [comment]
Hi 
Maximum call stack size exceeded : 
 somewhere in your code function calling itself, that's maybe the reason of that error.
which commands actually you are running ... is it electron or web version.

**Comment by vijhhh2** [comment]
Check for any duplicate methods you have in your code
