### ISSUE TITLE
Re-building nodejs serialport module in electron-angular

### ISSUE THREAD

**Issue by astroame** [maximegris/angular-electron#384]
I have tried everything possible to get serialport (https://www.npmjs.com/package/serialport) to work in my electron-angular windows application to no success. I have been on this for over 1 week. When i tried to rebuild the module using this command: 
```.\node_modules\.bin\electron-rebuild.cmd```
i get the following error:

```


An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\T-Bills\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\T-Bills\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\T-Bills\\.electron-gyp\\5.0.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\T-Bills\\.electron-gyp\\5.0.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\T-Bills\\.electron-gyp\\5.0.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(365,5): warning MSB8003: Could not find VCInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
  unpack_sqlite_dep
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(365,5): warning MSB8003: Could not find VCInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3\build\deps\sqlite3.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3\build\deps\sqlite3.vcxproj]
  
  
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=5.0.2" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3\\lib\\binding\\electron-v5.0-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.1.0/{toolset}/" "--package_name=electron-v5.0-win32-x64.tar.gz" "--msvs_version=2015"
gyp ERR! cwd C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\T-Bills\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\T-Bills\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\T-Bills\\.electron-gyp\\5.0.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\T-Bills\\.electron-gyp\\5.0.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\T-Bills\\.electron-gyp\\5.0.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(365,5): warning MSB8003: Could not find VCInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
  unpack_sqlite_dep
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(365,5): warning MSB8003: Could not find VCInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3\build\deps\sqlite3.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3\build\deps\sqlite3.vcxproj]
  
  
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=5.0.2" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\xampp\\htdocs\\Dynosurd_Projects\\Laravel57-GainSh-RetailApp-V2\\Desktop_App_27-08-2019--08-06PM\\angular_8-electron_5_Main\\node_modules\\sqlite3\\lib\\binding\\electron-v5.0-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.1.0/{toolset}/" "--package_name=electron-v5.0-win32-x64.tar.gz" "--msvs_version=2015"
gyp ERR! cwd C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\sqlite3
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\xampp\htdocs\Dynosurd_Projects\Laravel57-GainSh-RetailApp-V2\Desktop_App_27-08-2019--08-06PM\angular_8-electron_5_Main\node_modules\rxjs\internal\Subscriber.js:143:22)
```

 My code:

    ```maint.ts```

```
import { app, BrowserWindow, screen, ipcMain, shell, Menu } from 'electron';
import * as path from 'path';
import * as url from 'url';


import * as SerialPort from 'serialport';



  ipcMain.on("send-text-to-pole", async (event: any, comNameComPort: any, msg: any) => {
   

      const port =  new SerialPort(comNameComPort, { baudRate: 9600 }, function (err) {
        if (err) {
          console.log('Error: ', err.message);
          return;
        }
      });


      port.write(Buffer.from("                                         "));
      port.write(Buffer.from(msg), function(err: { message: any; }) {
        if (err) {
          console.log('Error on write: ', err.message);
          return;
        }
        console.log('message written')
      });
   

  });

```

  ```Node: 10.16.3
  Electron: 5.0.2
  Angular: 8.0.0
  Npm: 6.9.0
  serialport: 7.1.5
 Operating System: Windows 10 Pro
```

  Link to angular-electron boiler-plate : https://github.com/maximegris/angular-electron

**Comment by Ronalses** [comment]
I have the same error

**Comment by Ronalses** [comment]
I found a solution for this:

Follow the steps explained in this post: https://serialport.io/docs/guide-installation#electron

You must import the serialport in the electron.service.ts service

import * as serialport from 'serialport';

you must declare serialport: typeof serialport;

you must also import it in the constructor

this.serialport = window.require ('serialport');

![image](https://user-images.githubusercontent.com/20784993/65623620-976f6e80-df9e-11e9-982c-783e89e3910b.png)

![image](https://user-images.githubusercontent.com/20784993/65623650-aa823e80-df9e-11e9-9d9f-ebf48e259286.png)

**Comment by maximegris** [comment]
Thans @Ronalses that the good way to import NodeJS native libs in this project :)

**Comment by posti85** [comment]
Thank you. Now I'm facing is the following error in the console:
```
ERROR Error: The module '\\?\C:\angular-electron\node_modules\@serialport\bindings\build\Release\bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
But I don't know how to solve it...
