### ISSUE TITLE
npm run electron:windows FAILED

### ISSUE THREAD

**Issue by ArizonaInkStudios** [maximegris/angular-electron#404]
This is a fresh clone of master.

I am using VSCode to build and run the app. When I do `npm electron:local` it loads just fine. This is only an issue when I try to do a build with electron-builder and did not know if anyone had any insights? I included the log of the build if that helps.

Side note, I did run the same build in a command prompt and in a bash terminal and got the same results.

```
Executing task: npm run electron:windows


angular-electron@6.3.0 electron:windows X:\NodeProjects\angular-electron-master
npm run build:prod && electron-builder build --windows


angular-electron@6.3.0 build:prod X:\NodeProjects\angular-electron-master
npm run build -- -c production


angular-electron@6.3.0 build X:\NodeProjects\angular-electron-master
npm run postinstall:electron && npm run electron:serve-tsc && ng build "-c" "production"


angular-electron@6.3.0 postinstall:electron X:\NodeProjects\angular-electron-master
node postinstall


angular-electron@6.3.0 electron:serve-tsc X:\NodeProjects\angular-electron-master
tsc -p tsconfig-serve.json


chunk {0} runtime.69aad174de386c36a16c.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.34706bba241df5b7b9f9.js (main) 332 kB [initial] [rendered]
chunk {2} polyfills.2a21f6e436f0f87fc871.js (polyfills) 48.6 kB [initial] [rendered]
chunk {3} polyfills-es5.b5a721cda34b3d7c462a.js (polyfills-es5) 128 kB [initial] [rendered]
chunk {4} styles.8be1194c24da753d57a8.css (styles) 41 bytes [initial] [rendered]
Date: 2019-11-01T22:27:52.786Z - Hash: 70d65e0247282ccd38bd - Time: 38273ms
  • electron-builder  version=21.2.0 os=10.0.18362
  • loaded configuration  file=X:\NodeProjects\angular-electron-master\electron-builder.json
  • writing effective config  file=release\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=7.0.0 appOutDir=release\win-unpacked
  • building        target=portable file=release\angular-electron 6.3.0.exe archs=x64
  ⨯ [object Object]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@6.3.0 electron:windows: `npm run build:prod && electron-builder build --windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@6.3.0 electron:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     Y:\Users\{user}\AppData\Roaming\npm-cache\_logs\2019-11-01T22_28_47_118Z-debug.log
The terminal process terminated with exit code: 1
```

**Comment by cheplv** [comment]
@ArizonaInkStudios Can you provide build log (last ERR line). Seems that this is related to your build stack deps.

**Comment by ArizonaInkStudios** [comment]
Sure thing!
Log File from today:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'electron:windows'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'preelectron:windows', 'electron:windows', 'postelectron:windows' ]
5 info lifecycle angular-electron@6.3.0~preelectron:windows: angular-electron@6.3.0
6 info lifecycle angular-electron@6.3.0~electron:windows: angular-electron@6.3.0
7 verbose lifecycle angular-electron@6.3.0~electron:windows: unsafe-perm in lifecycle true
8 verbose lifecycle angular-electron@6.3.0~electron:windows: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Projects\angular-electron-master\node_modules\.bin;c:\program files (x86)\common files\intel\shared libraries\redist\intel64\compiler;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\git\cmd;c:\program files\common files\autodesk shared\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\microsoft\web platform installer\;c:\program files\dotnet\;c:\program files (x86)\microsoft sql server\110\dts\binn\;c:\program files (x86)\microsoft sql server\120\dts\binn\;c:\program files (x86)\microsoft sql server\130\dts\binn\;c:\windows\system32\openssh\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;;Y:\Users\{user}\AppData\Local\Microsoft\WindowsApps;Y:\Users\{user}\AppData\Roaming\npm;Y:\Users\{user}\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle angular-electron@6.3.0~electron:windows: CWD: D:\Projects\angular-electron-master
10 silly lifecycle angular-electron@6.3.0~electron:windows: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run build:prod && electron-builder build --windows'
10 silly lifecycle ]
11 silly lifecycle angular-electron@6.3.0~electron:windows: Returned: code: 1  signal: null
12 info lifecycle angular-electron@6.3.0~electron:windows: Failed to exec electron:windows script
13 verbose stack Error: angular-electron@6.3.0 electron:windows: `npm run build:prod && electron-builder build --windows`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid angular-electron@6.3.0
15 verbose cwd D:\Projects\angular-electron-master
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "electron:windows"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error angular-electron@6.3.0 electron:windows: `npm run build:prod && electron-builder build --windows`
22 error Exit status 1
23 error Failed at the angular-electron@6.3.0 electron:windows script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ArizonaInkStudios** [comment]
Also for help:
```
npm -v
6.12.0

node -v
v12.13.0

ng --version
Your global Angular CLI version (8.3.14) is greater than your local
version (8.3.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.6
Node: 12.13.0
OS: win32 x64
Angular: 8.2.12
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by cheplv** [comment]
@ArizonaInkStudios think that something with your win build dependencies - will try to build now with docker image: https://www.electron.build/multi-platform-build
Will give feedback to you

**Comment by ArizonaInkStudios** [comment]
@cheplv Thank you for your help! Let me know what I can do to assist.

**Comment by cheplv** [comment]
@ArizonaInkStudios Seems that docker is good to build for windows without any errors.
Steps to build:
1) Install docker on your local machine: https://docs.docker.com/docker-for-windows/install/
2) run: docker run --rm -ti -v ${PWD}:/project -v ~/.cache:/root/.cache electronuserland/builder:wine /bin/bash -c "npm install && npm run electron:windows"

this will build you app into release folder of project
cached folder needed to prevent every time you build project downloading or deps

**Comment by ArizonaInkStudios** [comment]
Can I do this without docker on just my Windows machine alone?

**Comment by cheplv** [comment]
@ArizonaInkStudios it's not good to use your standalone configuration, every env can contain different software etc (will produce questions like not building in my env etc every time on new device/user). Docker image contains all required dependencies to build. Much simplier if you use same build envs with docker image - it will helps you with CI integration. Use Docker and forget about that problems ))

**Comment by ArizonaInkStudios** [comment]
@cheplv sure sure. Id o notice that if run the build I get a release/win-unpacked folder. The angular-electron.exe is there and runs. Is this all that is needed? Am I missing something? I still get the error. I am guessing it is failing on the "packaging" step.

**Comment by cheplv** [comment]
@ArizonaInkStudios Yes - this all what you need. There is several possibilities to get executable - standalone exe, zip, nsis package (setup) as I remember. So next is up to you to dive deeper into builder configuration if you need this ))
https://www.electron.build/configuration/configuration

**Comment by ArizonaInkStudios** [comment]
Ok thank you! I am not sure why the last stage "Fails" but yet does not fail. LOL Thank you again @cheplv! I am going to try the Docker approach now and see if I get a different outcome.

**Comment by cheplv** [comment]
@ArizonaInkStudios Ping me back after your test with docker due i'm on linux.
May be in addition we will add docker build commands into readme to prevent such kind of questions

**Comment by ArizonaInkStudios** [comment]
@cheplv absolutely! Trying it now.

**Comment by ArizonaInkStudios** [comment]
@cheplv works like a charm! Yeah a docker tutorial would be helpful for those who are not using it! Thank you again!

**Comment by cheplv** [comment]
@ArizonaInkStudios welcome! ))
