### ISSUE TITLE
used ngx-quill，build error

### ISSUE THREAD

**Issue by ghost** [maximegris/angular-electron#405]
ERROR in ./node_modules/ngx-quill/fesm5/ngx-quill.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (F:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (F:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (F:\angular-electron\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (F:\angular-electron\node_modules\typescript\lib\typescript.js:16857:24)
    at checkNodeForDecorators (F:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (F:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (F:\angular-electron\node_modules\typescript\lib\typescript.js:16752:21)
    at checkNodeForDecorators (F:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (F:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (F:\angular-electron\node_modules\typescript\lib\typescript.js:16809:24)
    at checkNodeForDecorators (F:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (F:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (F:\angular-electron\node_modules\typescript\lib\typescript.js:16820:24)
    at checkNodeForDecorators (F:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (F:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (F:\angular-electron\node_modules\typescript\lib\typescript.js:16716:21)[0m

but normal angular project is nothing.

**Comment by maximegris** [comment]
Hi,

Please check https://github.com/KillerCodeMonkey/ngx-quill/issues/573#issuecomment-542603349

I close this issue here because it is an angular + typescript problem when it builds for production.
