### ISSUE TITLE
How to build project on raspberry pi 3

### ISSUE THREAD

**Issue by agnoam** [maximegris/angular-electron#463]
Hey, 
I'm using this repository with my project. 
I'm trying to build my project into Raspberry pi 3 b+ running Raspbian Debian based linux.

I tried to build with `npm run electron:linux` but it throws an exception: 
```
⨯ Unsupported arch arm  stackTrace=
                            Error: Unsupported arch arm
                                at archFromString (/home/pi/my_app/node_modules/builder-util/src/arch.ts:43:13)
                                at computeArchToTargetNamesMap (/home/pi/my_app/node_modules/app-builder-lib/src/targets/targetFactory.ts:30:24)
                                at Packager.doBuild (/home/pi/my_app/node_modules/app-builder-lib/src/packager.ts:429:41)
                                at Packager._build (/home/pi/my_app/node_modules/app-builder-lib/src/packager.ts:373:57)
```

**Comment by MrSurana** [comment]
I don't have a Raspberry PI but this seems to be a CPU architecture problem.
Try running this command to build for the ARM CPU

`npm run build:prod && electron-builder build --linux --armv7l`

instead of `npm run electron:linux`
