### ISSUE TITLE
node-gyp.js error

### ISSUE THREAD

**Issue by PadRocha** [maximegris/angular-electron#485]
I have this issue 
```
  • rebuilding native dependencies  dependencies=canvas@2.6.1 platform=win32 arch=x64
cannot execute  cause=exit status 1
                    out=
    > canvas@2.6.1 install D:\node\catalogo\angular-electron\node_modules\canvas
    > node-pre-gyp install --fallback-to-build


    D:\node\catalogo\angular-electron\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\proch\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" clean )
    Failed to execute 'node-gyp.cmd clean' (1)

                    errorOut=node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-electron-v8.2-win32-unknown-x64.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and electron@8.2.5 (electron-v8.2 ABI, unknown) (falling back to source compile with node-gyp)
    internal/modules/cjs/loader.js:976
      throw err;
      ^

    Error: Cannot find module 'D:\usr\local\lib\node_modules\node-gyp\bin\node-gyp.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
        at Function.Module._load (internal/modules/cjs/loader.js:855:27)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
        at internal/main/run_main_module.js:17:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
    }
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd clean' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Node\catalogo\angular-electron\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    node-pre-gyp ERR! System Windows_NT 10.0.18363
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Node\\catalogo\\angular-electron\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd D:\node\catalogo\angular-electron\node_modules\canvas
    node-pre-gyp ERR! node -v v13.6.0
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the canvas@2.6.1 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\proch\AppData\Roaming\npm-cache\_logs\2020-06-03T14_45_01_751Z-debug.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\proch\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js' rebuild canvas@2.6.1
                    workingDir=
```
I think is the problem with ngx-tui-image-editor :c

**Comment by PadRocha** [comment]
I tried everything and I need that ngx :c
