### ISSUE TITLE
E2E Test Failing

### ISSUE THREAD

**Issue by colinskow** [maximegris/angular-electron#533]
Apparently [`this.app`](https://github.com/maximegris/angular-electron/blob/master/e2e/main.e2e.ts#L13) is undefined.

Steps to reproduce:

1) Clone master, npm install
2) `npm run e2e`

```
1) angular-electron App
       "before each" hook for "creates initial windows":
     javascript error: javascript error: Cannot convert undefined or null to object
  (Session info: chrome=83.0.4103.122)
      at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:121:10)
      at WebDriverRequest._request (node_modules/webdriver/build/request.js:149:56)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:74:23)
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:74:23)
```

**Comment by colinskow** [comment]
SOLVED. Remote module must be enabled for Spectron to connect.
https://github.com/maximegris/angular-electron/blob/master/main.ts#L23
