### ISSUE TITLE
NODE_MODULE_VERSION mismatch when adding third party native modules

### ISSUE THREAD

**Issue by balihoo-jflitton** [maximegris/angular-electron#62]
I'm trying to add a native module (specifically [keytar](https://github.com/atom/node-keytar)).  When I attempt to use the module in my angular code I get the following error:

```
Uncaught Error: The module '/Volumes/Code/angular-electron/dist/node_modules/keytar/build/Release/keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Code/angular-electron/dist/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/Volumes/Code/angular-electron/dist/node_modules/keytar/lib/keytar.js:55:3)
```

Steps to reproduce:
```
git clone https://github.com/maximegris/angular-electron.git
cd angular-electron
npm install
npm install keytar --save
```
Add the following to webpack.config in the externals section:
```
"keytar": "require('keytar')"
```
Add the following to src/app/app.component.ts:
```
import * as keytar from 'keytar';
console.log(keytar);
```
Then start
``` npm start```

I'm using macOS with node 8.6.0.  Any ideas what I'm doing wrong?

**Comment by maximegris** [comment]
When this type of version mismatch occurs, you can either choose an electron distribution with the target Node version or rebuild the npm package.

See https://electron.atom.io/docs/tutorial/using-native-node-modules/
