### ISSUE TITLE
Linux/Mac Action build (14.x, 16.x, 17.x) fails with 2 errors

### ISSUE THREAD

**Issue by charlesr1971** [maximegris/angular-electron#664]
**Describe the bug**
Linux/Mac Action build (14.x, 16.x, 17.x) fails with 2 errors:

```
Error #1 --------------------------------------------------------------------------------
58
Error: EEXIST: file already exists, link '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/app/node_modules/body-parser/HISTORY.md' -> '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/release/linux-unpacked/resources/app/node_modules/body-parser/HISTORY.md'
59

60
Error #2 --------------------------------------------------------------------------------
61
Error: EEXIST: file already exists, link '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/app/node_modules/body-parser/LICENSE' -> '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/release/linux-unpacked/resources/app/node_modules/body-parser/LICENSE'  failedTask=build stackTrace=Error: Cannot cleanup: 
```

**To Reproduce**
1. Go to repository, after push
2. Click on Actions tab
3. Both Linux & Mac Actions fail for all 3 versions of NodeJs

**Expected behavior**
I expected the build to succeed. 
Everything works fine on Windows for all 3 versions of NodeJs. 

**Screenshots**

**Additional context**
 - OS: Linux & Mac

**Comment by charlesr1971** [comment]
Here is the full error stack:

```
Run npm run electron:build
2
  npm run electron:build
3
  shell: /bin/bash -e {0}
4

5
> twitter-circle-app-angular-v5@5.0.0 electron:build /home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5
6
> npm run build:prod && electron-builder build --publish=never
7

8

9
> twitter-circle-app-angular-v5@5.0.0 build:prod /home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5
10
> npm run build -- -c production
11

12

13
> twitter-circle-app-angular-v5@5.0.0 build /home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5
14
> npm run electron:serve-tsc && ng build --base-href ./ "-c" "production"
15

16

17
> twitter-circle-app-angular-v5@5.0.0 electron:serve-tsc /home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5
18
> tsc -p tsconfig.serve.json
19

20
- Generating browser application bundles (phase: setup)...
21
- ngx-colors [es2015/esm2015] (git+https://github.com/KroneCorylus/ngx-colors.git)
22
✔ Browser application bundle generation complete.
23
✔ Browser application bundle generation complete.
24
- Copying assets...
25
✔ Copying assets complete.
26
- Generating index html...
27
✔ Index html generation complete.
28

29
Initial Chunk Files           | Names         |     Size
30
styles.3f6f1ddfb3b9feb4.css   | styles        |  4.00 MB
31
main.f0d25ed72b646232.js      | main          |  1.08 MB
32
polyfills.0d8cc7b169ebc1ee.js | polyfills     | 40.22 kB
33
runtime.6ec74887c87a13bc.js   | runtime       |  2.48 kB
34

35
| Initial Total |  5.12 MB
36

37
Build at: 2021-12-21T20:42:06.628Z - Hash: ec5f2adb4eef3e50 - Time: 68472ms
38

39
Warning: /home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/node_modules/@angular/core/fesm2020/core.mjs depends on 'rxjs'. CommonJS or AMD dependencies can cause optimization bailouts.
40
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
41

42
Warning: /home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/node_modules/@angular/core/fesm2020/core.mjs depends on 'rxjs/operators'. CommonJS or AMD dependencies can cause optimization bailouts.
43
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
44

45
Warning: /home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/src/app/home/home.component.ts depends on 'twitter-lite'. CommonJS or AMD dependencies can cause optimization bailouts.
46
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
47

48

49
  • electron-builder  version=22.13.1 os=5.4.0-1064-azure
50
  • loaded configuration  file=/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/electron-builder.json
51
  • packaging       platform=linux arch=x64 electron=16.0.0 appOutDir=release/linux-unpacked
52
  • downloading     url=https://github.com/electron/electron/releases/download/v16.0.0/electron-v16.0.0-linux-x64.zip size=99 MB parts=4
53
  • downloaded      url=https://github.com/electron/electron/releases/download/v16.0.0/electron-v16.0.0-linux-x64.zip duration=435ms
54
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
55
  ⨯ Cannot cleanup: 
56

57
Error #1 --------------------------------------------------------------------------------
58
Error: EEXIST: file already exists, link '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/app/node_modules/body-parser/HISTORY.md' -> '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/release/linux-unpacked/resources/app/node_modules/body-parser/HISTORY.md'
59

60
Error #2 --------------------------------------------------------------------------------
61
Error: EEXIST: file already exists, link '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/app/node_modules/body-parser/LICENSE' -> '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/release/linux-unpacked/resources/app/node_modules/body-parser/LICENSE'  failedTask=build stackTrace=Error: Cannot cleanup: 
62
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Error #1 --------------------------------------------------------------------------------
63
Error: EEXIST: file already exists, link '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/app/node_modules/body-parser/HISTORY.md' -> '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/release/linux-unpacked/resources/app/node_modules/body-parser/HISTORY.md'
64
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Error #2 --------------------------------------------------------------------------------
65
Error: EEXIST: file already exists, link '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/app/node_modules/body-parser/LICENSE' -> '/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/release/linux-unpacked/resources/app/node_modules/body-parser/LICENSE'
66
    at throwError (/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/node_modules/builder-util/src/asyncTaskManager.ts:88:11)
67
    at checkErrors (/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
68
    at AsyncTaskManager.awaitTasks (/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/node_modules/builder-util/src/asyncTaskManager.ts:67:7)
69
    at Object.copyAppFiles (/home/runner/work/twitter-circle-app-angular-v5/twitter-circle-app-angular-v5/node_modules/app-builder-lib/src/util/appFileCopier.ts:77:7)
70
From previous event:
71
    at processImmediate (internal/timers.js:464:21)
72
npm ERR! code ELIFECYCLE
73
npm ERR! errno 1
74
npm ERR! twitter-circle-app-angular-v5@5.0.0 electron:build: `npm run build:prod && electron-builder build --publish=never`
75
npm ERR! Exit status 1
76
npm ERR! 
77
npm ERR! Failed at the twitter-circle-app-angular-v5@5.0.0 electron:build script.
78
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
79

80
npm ERR! A complete log of this run can be found in:
81
npm ERR!     /home/runner/.npm/_logs/2021-12-21T20_42_10_502Z-debug.log
82
Error: Process completed with exit code 1.

```

**Comment by maximegris** [comment]
Hi

[The last build](https://github.com/maximegris/angular-electron/actions/runs/1893038950)  was successful

Regards
