### ISSUE TITLE
Uncaught TypeError: path.join is not a function

### ISSUE THREAD

**Issue by mvuc87** [maximegris/angular-electron#746]
**Describe the bug**
1. git clone <main_branch_angular_15>
2. step into cloned directory
3. run `npm i`
4. run `npm start`

I am getting:
```
Uncaught TypeError: path.join is not a function
    at 2218 (index.js:4:23)
    at __webpack_require__ (bootstrap:19:1)
    at 3256 (earnings.pipe.ts:7:26)
    at __webpack_require__ (bootstrap:19:1)
    at 6747 (app.component.html:1:79)
    at __webpack_require__ (bootstrap:19:1)
    at 4431 (preview.component.html:2:40)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (ignored|C:\temp\interview\interview-test\node_modules\electron|path:1:1)
    at ignored|C:\temp\interview\interview-test\node_modules\electron|path:1:1
```

**To Reproduce**
Reproducible each time on start

**Expected behavior**
Error not to appear.

**Additional context**
 - OS: Windows 10
 - Node: v18.14.2

**Comment by thamizh-qwerty** [comment]
This error message usually indicates that the path module is not properly imported or initialized in your code.

To fix this error, you need to make sure that you have imported the path module correctly. In Node.js, you can import the path module using the following code:

const path = require('path');

**Comment by maximegris** [comment]
No activity on this issue since February. I close it.
