### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by Kamar-Meddah** [maximegris/angular-electron#80]
when i run `npm run electron:windows or npm run build:prod` it shows an error and it says that angular 5+ needs cli 1.5 ++
and i have both of them globaly and in the repo
please fix it as soon as possible

**Comment by shalomdotnet** [comment]
You need to update your global instance of angular-cli.
Try to run `npm update -g @angular/cli`.

**Comment by Kamar-Meddah** [comment]
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in
 'C:\Users\User\Documents\MyApps\angular\src'
resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\User\Documents\MyApp
s\angular\src'
  using description file: C:\Users\User\Documents\MyApps\angular\package.json (r
elative path: ./src)
  after using description file: C:\Users\User\Documents\MyApps\angular\package.j
son (relative path: ./src)
    using description file: C:\Users\User\Documents\MyApps\angular\package.json
(relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfa
ctory doesn't exist
      .ts
        C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfa
ctory.ts doesn't exist
      .js
        C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfa
ctory.js doesn't exist
      .scss
        C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfa
ctory.scss doesn't exist
      .json
        C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfa
ctory.json doesn't exist
      as directory
        C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfa
ctory doesn't exist
[C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfactory]
[C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfactory.t
s]
[C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfactory.j
s]
[C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfactory.s
css]
[C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfactory.j
son]
[C:\Users\User\Documents\MyApps\angular\src\$$_gendir\app\app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

ERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular
 CLI 1.5+
    at throwNotSupportedError (C:\Users\User\Documents\MyApps\angular\node_modul
es\@angular\compiler-cli\src\ngtools_api.js:78:11)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Users\User\Documents\MyApps
\angular\node_modules\@angular\compiler-cli\src\ngtools_api.js:31:15)
    at _donePromise.Promise.resolve.then (C:\Users\User\Documents\MyApps\angular
\node_modules\@ngtools\webpack\src\plugin.js:430:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
Child html-webpack-plugin for "index.html":
     1 asset
    [7GO9] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 377
 bytes {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-electron@2.0.0 build: `webpack --display-error-details && npm r
un build:electron:main`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-electron@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-11-15T20_38_16_6
31Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-electron@2.0.0 build:prod: `cross-env NODE_ENV=production npm r
un build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-electron@2.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-11-15T20_38_16_7
25Z-debug.log

**Comment by Kamar-Meddah** [comment]
the problem is with production mode only i've tried it without the prod flag and it worked

**Comment by francoisvdv** [comment]
Can confirm, also have this error,

Can't resolve './$$_gendir/app/app.module.ngfactory'

**Comment by yawor** [comment]
Same error as above. Global @angular/cli updated to latest (1.5.2).

**Comment by ktsepelev** [comment]
same error to

**Comment by baldwindc** [comment]
Same error here:
```
ERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (C:\Users\daniel\dev\angular-electron\node_modules\@angular\compiler-cli\src\ngtools_api.js:78:11)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Users\daniel\dev\angular-electron\node_modules\@angular\compiler-cli\src\ngtools_api.js:31:15)
    at _donePromise.Promise.resolve.then (C:\Users\daniel\dev\angular-electron\node_modules\@ngtools\webpack\src\plugin.js:430:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by marc101101** [comment]
Same here :(

`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src'
resolve './$$_gendir/app/app.module.ngfactory' in '/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src'
  using description file: /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/package.json (relative path: ./src)
  after using description file: /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/package.json (relative path: ./src)
    using description file: /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      .scss
        /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.scss doesn't exist
      .json
        /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.json doesn't exist
      as directory
        /Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory doesn't exist
[/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory]
[/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.ts]
[/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.js]
[/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.scss]
[/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory.json]
[/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/src/$$_gendir/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

ERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/node_modules/@angular/compiler-cli/src/ngtools_api.js:78:11)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/node_modules/@angular/compiler-cli/src/ngtools_api.js:31:15)
    at _donePromise.Promise.resolve.then (/Users/markusguder/workspace/ASE_WS1718-notenverwaltung/node_modules/@ngtools/webpack/src/plugin.js:430:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3`

**Comment by maximegris** [comment]
Problem fixed.
You can pull the repo (master branch or 2.1.0 tag);
Please follow those steps if you want to fix this mannually,  : 

1/ In `webpack.config.js`, replace AotPlugin to AngularCompilerPlugin
* line 13
```javascript 
const { AngularCompilerPlugin } = require('@ngtools/webpack');
```
* line 168:
```javascript
    plugins.push(new AngularCompilerPlugin({
      entryModule: "src/app/app.module#AppModule",
      "mainPath": "main.ts",
      "hostReplacementPaths": {
        "environments/index.ts": "environments/index.prod.ts"
      },
      "exclude": [],
      "tsConfigPath": "src/tsconfig.app.json"
    }));
```

2/ In tsconfig.ts , replace value of `AllowJs` from `true` to `false`. There is an issue in aot compilation with Angular 5 (https://github.com/angular/angular/issues/19757)

It should fix the problem.

**Comment by Kamar-Meddah** [comment]
it worked but there still a sass loader error when i modify the code so i use only css it work normally here is the error msg

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/styles.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:924:18)
    at Object.getInstalledBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\extensions.js:128:13)
    at foundBinariesList (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18
 @ ./src/styles.scss 4:14-204
 @ multi ./src/styles.scss

ERROR in Error: Child compilation failed:
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:924:18)
    at Object.getInstalledBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\extensions.js:128:13)
    at foundBinariesList (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18:
Error: ENOENT: no such file or directory, scandir 'C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\vendor'
    at childCompiler.runAsChild (C:\Users\User\Documents\MyApps\angular-electron\node_modules\@ngtools\webpack\src\resource_loader.js:53:28)
    at compile (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compiler.js:304:11)
    at applyPluginsAsync.err (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compiler.js:514:14)
    at next (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:206:13)
    at compilation.seal.err (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:195:46)
    at self.applyPluginsAsync.err (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compilation.js:680:19)
    at Compilation.applyPluginsAsyncSeries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:195:46)
    at self.applyPluginsAsync.err (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compilation.js:671:11)
    at next (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\index.js:244:6)
    at Compilation.applyPluginsAsyncSeries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compilation.js:666:10)
    at Compilation.applyPluginsAsyncSeries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:195:46)
    at sealPart2 (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compilation.js:662:9)
    at Compilation.applyPluginsAsyncSeries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:195:46)
    at Compilation.seal (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compilation.js:605:8)
    at applyPluginsParallel.err (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compiler.js:508:17)
    at C:\Users\User\Documents\MyApps\angular-electron\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\User\Documents\MyApps\angular-electron\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Child src\app\components\home\home.component.html:
     1 asset
       1 module
Child html-webpack-plugin for "index.html":
     1 asset
    [7GO9] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 377 bytes {0} [built]
Child src\app\app.component.html:
     1 asset
    [5xMp] ./src/app/app.component.html 55 bytes {0} [built]
Child src\app\components\home\home.component.scss:
     1 asset
       1 module

    ERROR in ./src/app/components/home/home.component.scss
    Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\vendor'
        at Object.fs.readdirSync (fs.js:924:18)
        at Object.getInstalledBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\extensions.js:128:13)
        at foundBinariesList (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:20:15)
        at foundBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:15:5)
        at Object.module.exports.missingBinary (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:45:5)
        at module.exports (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\binding.js:15:30)
        at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:641:30)
        at Object.Module._extensions..js (module.js:652:10)
        at Module.load (module.js:560:32)
        at tryModuleLoad (module.js:503:12)
        at Function.Module._load (module.js:495:3)
        at Module.require (module.js:585:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (module.js:641:30)
        at Object.Module._extensions..js (module.js:652:10)
        at Module.load (module.js:560:32)
        at tryModuleLoad (module.js:503:12)
        at Function.Module._load (module.js:495:3)
        at Module.require (module.js:585:17)
        at require (internal/module.js:11:18)
        at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18
Child src\app\app.component.scss:
     1 asset
    [sQHO] ./src/app/app.component.scss 2.84 kB {0} [built] [failed] [1 error]

    ERROR in ./src/app/app.component.scss
    Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\vendor'
        at Object.fs.readdirSync (fs.js:924:18)
        at Object.getInstalledBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\extensions.js:128:13)
        at foundBinariesList (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:20:15)
        at foundBinaries (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:15:5)
        at Object.module.exports.missingBinary (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\errors.js:45:5)
        at module.exports (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\binding.js:15:30)
        at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:641:30)
        at Object.Module._extensions..js (module.js:652:10)
        at Module.load (module.js:560:32)
        at tryModuleLoad (module.js:503:12)
        at Function.Module._load (module.js:495:3)
        at Module.require (module.js:585:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\User\Documents\MyApps\angular-electron\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (module.js:641:30)
        at Object.Module._extensions..js (module.js:652:10)
        at Module.load (module.js:560:32)
        at tryModuleLoad (module.js:503:12)
        at Function.Module._load (module.js:495:3)
        at Module.require (module.js:585:17)
        at require (internal/module.js:11:18)
        at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\User\Documents\MyApps\angular-electron\node_modules\loader-runner\lib\LoaderRunner.js:173:18
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-electron@2.1.0 build: `webpack --display-error-details && npm run build:electron:main`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-electron@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-11-18T19_44_46_766Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-electron@2.1.0 build:prod: `cross-env NODE_ENV=production npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-electron@2.1.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-11-18T19_44_46_924Z-debug.log

**Comment by maximegris** [comment]
Webpack configuration had changed a lot between Angular 4 and Angular 5 projects.
I wish you to have a look at `package.json` and `webpack.config.js` (on master). Replace your current files by those one and make a `npm install`
The new Webpack configuration is inspired by Angular 5's one.
If you still have errors, please report them in another issue.

**Comment by JoshuaFreak** [comment]
Where I can find the webpack.config? I cant find it. @maximegris
